language: python
python:
  - 3.11
install:
  - pip install -r requirements.txt
  - pip install -r requirements-development.txt
script:
  - flake8 .
  - pylint --recursive=y .
  - ls -al tests/user/user_log_samples
  - coverage run tests/test_runner.py
  - coverage report -m