name: pyRACF Linting & Unit Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-versions: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry env info
        poetry install --no-root
    - name: Flake8
      run: poetry run flake8 .
    - name: Pylint
      run: poetry run pylint --recursive=y .
    - name: Unit Test
      run: poetry run coverage run tests/test_runner.py
    - name: Code Coverage
      run: poetry run coverage report -m
