name: pyRACF package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements-development.txt
    - name: Lint
      run: |
        flake8 .
        pylint --recursive=y .
    - name: Unit test
      run: |
        python3 tests/test_runner.py
    - name: Coverage report
      run: |
        coverage run tests/test_runner.py
        coverage report -m