name: pyRACF package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-development.txt
    - name: Test with pytest
      run: |
        flake8 .
        pylint --recursive=y .
        coverage run tests/test_runner.py
        coverage report -m